services:
  monik:
    build: .

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./config:/opt/monik/config
      - ./data:/opt/monik/data

    command:
      - python
      - -m
      - main
