-- ==========================================================
-- Table: diagnostic_events
-- Responsibility:
--   Stores diagnostic events generated by the application.
-- ==========================================================

CREATE TABLE IF NOT EXISTS diagnostic_events (
    id INTEGER PRIMARY KEY,

    severity TEXT NOT NULL,
    source TEXT NOT NULL,

    message TEXT NOT NULL,

    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_diagnostic_events_severity
ON diagnostic_events(severity);

CREATE INDEX IF NOT EXISTS idx_diagnostic_events_created_at
ON diagnostic_events(created_at);
